//! Compile the bundled SolidWorks appearance library into the crate.
//!
//! There are 619 `.p2m` files and 332 KB of text between them, and they are the
//! only statement anywhere of how a *finish* looks — a `.sldmat` says what a
//! part is made of, an appearance says whether it was powder-coated or
//! polished. Generating the table here rather than listing the files by hand
//! keeps the tree on disk the single source of truth: add an appearance and it
//! is in the next build.
//!
//! The `.p2m` files are all read. Their textures are not: the tree beside them
//! is 255 MB of images across 349 files, and a converter carrying all of that
//! would be a converter nobody installs. Only the finishes the resolver can
//! actually select bring their images with them — see `TEXTURED_FINISHES`
//! below, which a test holds against `p2m::representative`.
//!
//! If the image tree is absent — it is not in the repository — the table comes
//! out empty and the converter behaves exactly as it did before textures
//! existed. That is the state of a fresh clone, and it must build.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// The appearances whose images are carried in the binary.
///
/// Exactly the finishes `p2m::representative` can return, and a test in that
/// module fails if the two lists ever drift apart. Adding one here costs
/// whatever its images weigh, so the list is meant to stay short.
const TEXTURED_FINISHES: &[&str] = &[
    "painted/powder coat/dark powdercoat",
    "painted/car/gloss blue",
];

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("assets/Materials");
    println!("cargo:rerun-if-changed=assets/Materials");

    let mut files = Vec::new();
    walk(&root, &mut files);
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs from assets/Materials. Do not edit.\n\
         pub(crate) static BUNDLED_APPEARANCES: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        let key = path
            .strip_prefix(&root)
            .expect("walked from root")
            .to_string_lossy()
            .replace('\\', "/")
            .to_lowercase();
        let key = key.strip_suffix(".p2m").unwrap_or(&key).to_string();
        let _ = writeln!(
            out,
            "    ({key:?}, include_str!({:?})),",
            path.to_string_lossy()
        );
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("appearances.rs"), out).expect("write the appearance table");

    write_textures(&root, &out_dir);
}

/// Emit `BUNDLED_TEXTURES`: the images named by the finishes above, keyed by
/// the same normalised path the parser produces.
fn write_textures(materials: &Path, out_dir: &Path) {
    let assets = materials.parent().expect("assets/Materials has a parent");
    println!("cargo:rerun-if-changed=assets/Images");
    println!("cargo:rerun-if-changed=assets/generated");

    let mut wanted: Vec<String> = Vec::new();
    for finish in TEXTURED_FINISHES {
        let file = materials.join(format!("{finish}.p2m"));
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        for line in text.lines() {
            let line = line.trim();
            let raw = if let Some(rest) = line.strip_prefix("color texture ") {
                rest.split('"').nth(3)
            } else if let Some(rest) = line.strip_prefix("\"bumpTexture\" ") {
                rest.split('"').nth(1)
            } else {
                None
            };
            if let Some(path) = raw.and_then(normalise) {
                if !wanted.contains(&path) {
                    wanted.push(path);
                }
            }
        }
    }
    wanted.sort();

    // Colour images whose level has been divided out, by tools/make_grain.py.
    //
    // A SolidWorks colour image is the appearance's own colour times a grain
    // whose mean is one, and multiplying a part's colour by it applies that
    // level twice. glTF's base colour factor stops at one, so a part brighter
    // than the appearance cannot be compensated for afterwards — the pilot's
    // dominant paint needs 1.12 and its blue needs 2.44, and both came out
    // clamped to white. So the grain is prepared separately and shipped
    // instead of the image, and the number to multiply back by comes with it.
    let grains = read_grains(&assets.join("generated/grains.txt"));

    let mut out = String::from(
        "// Generated by build.rs from assets/Images. Do not edit.\n\
         pub(crate) static BUNDLED_TEXTURES: &[(&str, &[u8], f32)] = &[\n",
    );
    let mut found = 0;
    for path in &wanted {
        let file = path.rsplit('/').next().unwrap_or(path);
        let (real, level) = match grains.iter().find(|(name, _, _)| name == file) {
            Some((_, generated, level)) => {
                (Some(assets.join("generated").join(generated)), *level)
            }
            // The tree on disk is not lower-cased; the reference is. Find the
            // real file by walking the components case-insensitively.
            None => (resolve(assets, path), 1.0),
        };
        let Some(real) = real.filter(|p| p.is_file()) else {
            continue;
        };
        let _ = writeln!(
            out,
            "    ({path:?}, include_bytes!({:?}), {level:?}),",
            real.to_string_lossy()
        );
        found += 1;
    }
    out.push_str("];\n");
    // Silence when it worked. A missing image is not fatal — the converter
    // simply has no texture for that finish — but it is worth saying.
    if found < wanted.len() {
        println!(
            "cargo:warning=only {found} of {} finish textures found under assets/Images; \
             those finishes will convert without them",
            wanted.len()
        );
    }
    std::fs::write(out_dir.join("textures.rs"), out).expect("write the texture table");
}

/// The grain manifest: the image it came from, the file that replaced it, and
/// the mean it ended up with after clipping.
fn read_grains(path: &Path) -> Vec<(String, String, f32)> {
    let Ok(text) = std::fs::read_to_string(path) else {
        return Vec::new();
    };
    text.lines()
        .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty())
        .filter_map(|line| {
            let mut parts = line.split('\t');
            Some((
                parts.next()?.to_string(),
                parts.next()?.to_string(),
                parts.next()?.parse().ok()?,
            ))
        })
        .collect()
}

/// Lower case, forward slashes, `..` resolved — the same shape `p2m` keys by.
fn normalise(raw: &str) -> Option<String> {
    let lowered = raw.trim().replace('\\', "/").to_lowercase();
    let mut parts: Vec<&str> = Vec::new();
    for part in lowered.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            _ => parts.push(part),
        }
    }
    (!parts.is_empty()).then(|| parts.join("/"))
}

/// Walk a normalised path against a tree whose names have their own case.
fn resolve(root: &Path, path: &str) -> Option<PathBuf> {
    let mut at = root.to_path_buf();
    for part in path.split('/') {
        let entry = std::fs::read_dir(&at).ok()?.flatten().find(|e| {
            e.file_name().to_string_lossy().to_lowercase() == part
        })?;
        at = entry.path();
    }
    at.is_file().then_some(at)
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.extension().is_some_and(|e| e.eq_ignore_ascii_case("p2m")) {
            out.push(path);
        }
    }
}
