//! Compile the bundled SolidWorks appearance library into the crate.
//!
//! There are 619 `.p2m` files and 332 KB of text between them, and they are the
//! only statement anywhere of how a *finish* looks — a `.sldmat` says what a
//! part is made of, an appearance says whether it was powder-coated or
//! polished. Generating the table here rather than listing the files by hand
//! keeps the tree on disk the single source of truth: add an appearance and it
//! is in the next build.
//!
//! Only the `.p2m` files are read. The textures beside them are hundreds of
//! megabytes of images the converter has no use for.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("assets/Materials");
    println!("cargo:rerun-if-changed=assets/Materials");

    let mut files = Vec::new();
    walk(&root, &mut files);
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs from assets/Materials. Do not edit.\n\
         pub(crate) static BUNDLED_APPEARANCES: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        let key = path
            .strip_prefix(&root)
            .expect("walked from root")
            .to_string_lossy()
            .replace('\\', "/")
            .to_lowercase();
        let key = key.strip_suffix(".p2m").unwrap_or(&key).to_string();
        let _ = writeln!(
            out,
            "    ({key:?}, include_str!({:?})),",
            path.to_string_lossy()
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("appearances.rs");
    std::fs::write(dest, out).expect("write the appearance table");
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, out);
        } else if path.extension().is_some_and(|e| e.eq_ignore_ascii_case("p2m")) {
            out.push(path);
        }
    }
}
